name: Staging App

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: lhr
  FLY_ORG: personal

jobs:
  staging_app:
    name: Staging App
    runs-on: ubuntu-latest
    permissions: write-all # ⚠️ I will find out what write:org means

    concurrency:
      group: pr-${{ github.event.number }}
    environment:
      name: pr-${{ github.event.number }}-hyphengolang-with-fly.io # pr-{number}-{repo_org}-{repo_name}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy App
        id: deploy
        uses: superfly/fly-pr-review-apps@1.0.0